# Generated by Django 3.2.9 on 2022-03-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220305_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default=jpg', upload_to='profile_pics'),
        ),
    ]
